### ISSUE TITLE
Request: More clarity on MusikCube and musikcube

### ISSUE THREAD

**Issue by Joshfindit** [clangen/musikcube#115]
As a fan of the 'old' version, it looks like this current version hits a lot of the same points (large library support, fast interactions (I assume), similar browsing style), but it would be awesome if the front page, the github readme, or a visually prominent page talked specifically about the connection between the two.

Is this a rewrite with the same ideas? A different front-end to code that was ported over? Written by the same team or a different team? And so-on.

With respect,
Josh

![](https://upload.wikimedia.org/wikipedia/commons/b/b4/MusikCube.PNG)

![capture](https://user-images.githubusercontent.com/1937155/28620849-1980bebc-71e5-11e7-8abb-ba81484b5484.JPG)

**Comment by stefanos82** [comment]
This is directly taken from their official website: https://musikcube.com/old/

Yes, they are the same project, but with a different path now.

**Comment by clangen** [comment]
Sorry it's so confusing. I was hoping enough time had passed that most people had forgotten about the original release so it wouldn't be a big deal. Just some context:

1. musikCube was completed in 2005
2. musikCube 2 started development in 2006. However, I ended up taking a job that prevented me from working on it further (conflict of interest). A couple other developers continued for a while, but the project was mostly abandoned by 2009.
3. Last year I picked up development again, but the original source had sort of rotted over time. I also wanted to create a truly cross-platform app this time around so I threw away the entire UI layer. I started prototyping improvements to the audio engine in a little command-line app. Over time it just sort of evolved into a fully-featured player.

I briefly considered renaming it to something else, but ultimately decided to keep the name (1) out of respect for the developers who spent a lot of time working on original foundation, and (2) because I already had the domain name and git repositories setup.

This is, however, a more complete version of the original musikCube 2, just with a different frontend.

**Comment by Joshfindit** [comment]
Awesome, thank you.

Just one more question: Are you the developer of musikCube v1? And if not, what's the path from them to you?

**Comment by clangen** [comment]
Yep, I'm the original developer of mC1. :)

**Comment by Joshfindit** [comment]
For the record, I've had thousands of mp3s since before 2005, and musikCube is in the top 3 pieces of software I miss every day (I'm on Mac now). The respect for metadata (and only writing to id3 when asked), the sheer speed, and the small mini player that included a search box. These are still things I can't find on OSX.
I'll be trying out the new one, thanks. ☺️
