### ISSUE TITLE
0.21.1 crashes on startup (OSX 10.11.6)

### ISSUE THREAD

**Issue by lillian27** [clangen/musikcube#124]
Downloaded osx binary bundle, extracted, and tried to run ./musikcube:

[~/Downloads/musikcube_macos_0.21.1]$ ./musikcube
Trace/BPT trap: 5

OSX 10.11.6, iTerm2 3.0.15, GNU bash 4.4.12

**Comment by curioussavage** [comment]
crashes on OSX 10.10.5 too
`Segmentation fault: 11`

**Comment by clangen** [comment]
Flagging as a build issue, as this is probably a problem with the way the app is getting packaged together. I'll try to take a look at this one after we smooth out compile issues with Fedora and ArchLinux.

**Comment by curioussavage** [comment]
Awesome. Can't wait to try it out.

**Comment by clangen** [comment]
I just realized you guys are using older releases of the operating system -- 10.11.x and 10.10.x. I have a sneaking suspicion that's the root cause, because I compiled this on a 10.12.x system. Are you guys able to install and run the homebrew version? 

If this is indeed problem with older versions of the operating system, I need to figure out how to compile a single binary that supports older OS releases.

**Comment by lillian27** [comment]
That's usually a good place to start which is why I included the os version.

I use Macports not Homebrew so after some hand-hacking (couldn't find boost headers, and plugin linking not finding libs) I was able to compile and run my own build.   So os version doesn't seem to be the issue.  Back to a packaging problem?

**Comment by urielz** [comment]
running into the same issue with musikcube 0.31.0 (Trace/BPT trap: 5) also using OS X 10.11.6. Also a macport user so brew is not really an option for me.

**Comment by ghost** [comment]
0.42.0 on 10.10.5 (OS X)

`  51173 trace trap  ./musikcube`

**Comment by clangen** [comment]
Closing old issues. Please re-open if this is still a problem.
