### ISSUE TITLE
support for openwrt

### ISSUE THREAD

**Issue by tristan-k** [clangen/musikcube#143]
Is it possible to run Musikcube on an openwrt installed arm router?

**Comment by clangen** [comment]
musikcube should generally be compatible with ARM processors -- it runs well on Raspberry Pi devices with Raspbian... but there is no explicit support for OpenWRT. 

If OpenWRT supports CMake you can install that, then try to build. 

Closing this issue for now because it's super old. Please re-open if you have additional questions.
