### ISSUE TITLE
streaming to musikdroid never starts playing

### ISSUE THREAD

**Issue by carnager** [clangen/musikcube#169]
I have matching releases of musikcube and musikdroid (0.31) on my desktop/phone and when i switch to streaming mode and start a song the app shows a spinning circle, but never actually starts playing a song.

Is this a known issue?

**Comment by clangen** [comment]
It's not a known issue, and works on my test devices and emulators. A couple questions -- are you trying to stream locally (i.e. over wifi on the same network), or remotely/over the internet? If the latter, you need to make sure you have both ports (default 7905 and 7906) exposed by your firewall.

However, if I had to guess, I'd say you're trying to stream a format that can't be be decoded by your Android phone. Are you trying to stream FLAC, by chance? I recently discovered our default playback module (ExoPlayer) doesn't support it out of the box.  You can try the following non-ideal solutions until I can figure out how to bundle FLAC support into the APK:

1. Enable the on-demand downsampler -- it'll convert the audio to MP3 on the fly. Just go into settings and scroll down and set a "streaming downsampler bitrate" to whatever you want. Obviously this isn't ideal because it compresses the audio.

2. Try changing the playback engine to MediaPlayer. It MAY play FLAC -- it depends if your version of the Android OS has a decoder (not all of them do). Similarly, go into preferences, scroll down to "playback engine" and select "MediaPlayer (deprecated)". Note that while this may work, you may experience bugs. MediaPlayer is not known for its stability, and the musikdroid integration with it is a bit lacking.

**Comment by carnager** [comment]
I cant find a downsampler option neither in 0.31 nor in master?
https://fb.53280.de/Ga6

**Comment by clangen** [comment]
Oh, sorry I wasn't more clear. The setting lives on the musikdroid Android app. Open the app > press the menu button in the upper right corner > Settings

**Comment by carnager** [comment]
it works, thanks!

**Comment by jlapaix** [comment]
Hello clangen. I've been having the same problem when upgrading from v21.0 to v31.0 but my library is only mp3s and streaming over the internet. Changing the downsampler to 320 works for me but I shouldn't have to correct?

**Comment by clangen** [comment]
Whoa. Yep. Non-downsampling streaming is broken in the Android client. It was a bug on the Android side -- I just uploaded v0.22.0 of the Android APK here to fix this problem: https://github.com/clangen/musikcube/releases/tag/0.31.0

**Comment by jlapaix** [comment]
Works now. Thanks!

**Comment by dkanada** [comment]
I think this might be broken again on the latest master. I have the same issue in streaming mode on my LAN using MP3 files, but enabling downsampling and restarting the app works.
