### ISSUE TITLE
Feature request: stream audio between different PCs (instead of just PC -> Android)

### ISSUE THREAD

**Issue by dvdmuckle** [clangen/musikcube#204]
It would be really useful if there were an endpoint in the HTTP server that would serve up either the current playing song, or a streaming endpoint ala the MPD streaming endpoint, which basically acts like an infinitely long music file that plays, including gaps for pausing, an audio stream of whatever is being played.

**Comment by clangen** [comment]
Yeah, I do want to do something like this. I'll have to research how MPD does it, but there are a couple different ways to accomplish something like this. Are you envisioning something like an shoutcast/icecast server?

**Comment by dvdmuckle** [comment]
I'm not sure how those work exactly, or how hard they are to do. A HTTP endpoint sounds like it would be a good start, considering there's already an HTTP server in `musikcore`.

**Comment by dkanada** [comment]
How does the http server currently function? When I saw that the project was using both http and websockets I assumed the http server acted as a music stream that the clients would just hook into, but now I am a bit unsure.

**Comment by dvdmuckle** [comment]
The HTTP server works by essentially exposing an HTTP server with _all_ of your music library at once, indexed by external_ids which you can get from the websocket endpoint. The idea this issue brings up is having a static endpoint on the HTTP server that plays a whatever musikcube is playing ala the MPD HTTPD output.


Speaking of, @clangen, I looked into shout/icecast a bit more, it looks like it's an HTTP server that also ships metadata in headers on what's playing. So, more features than the HTTPD output, but also probably harder to implement.

**Comment by dkanada** [comment]
@dvdmuckle interesting, I think websockets supports file streaming now so is there any specific reason for HTTP and websockets rather than a single protocol for the entire API?

@clangen have you ever considered making a couple of changes to the project to transition into a client-server model? There are a lot of people who would enjoy a music streaming server with officially supported ncurses clients across every major platform plus an extremely polished android client. The only things that would need work as far as I can tell are separating musikcube from musikcore just a bit more, modifying the core to only expose requested songs, and implementing user authentication with SSL support. I would be willing to help implement some of that regardless, pretty sure I am going to use this project to easily cache music on my phone.

EDIT: I just checked and it looks like the curses app heavily relies on the core. The changes wouldn't be nearly as straightforward as I thought considering musikcube doesn't currently access the core through the websocket and http servers. Does this mean the API was only created for musikdroid then?

**Comment by clangen** [comment]
Sorry for the slow response time here, work has been keeping me super busy recently.

@dvdmuckle -- I'll need to do a bit of research to understand how MPD's HTTPD output works. I agree something like this would be very cool, and hopefully not too difficult to implement. As you said, there's already an HTTP server built in, and I "recently" added support for encoder plugins, so we should be able to capture the raw audio data on its way to the output device via a DSP (or PCM Visualizer) plugin, then pipe it through an Encoder and out to a socket.

@dkanada -- unfortunately musikcube started life as a hacked-together prototype that I was just having fun with... it eventually evolved into something useful, but by that point it was pretty closely coupled with the core. I wanted to keep the project moving forward, so I decided to focus on making the core more plugable so it could support arbitrary clients. That resulted in the HTTP/WebSockets server, followed by the Android client. At some point I'd still like to go back and retrofit the main client to use the server, but as you said, it'd be a pretty large change.

**Comment by dkanada** [comment]
Would this feature be compatible with a client-server model though? I was looking through the code and if you pulled out all the playback stuff from the core there would really be no logical way to implement a current playback endpoint. I guess it technically depends on how you go about defining the role of the server in this case. Maybe if the server had a separate endpoint for the playback queue of each client. The remote feature would need some work as well to select a specific client for control come to think of it.

**Comment by dkanada** [comment]
I guess the first step would be deciding what kind of client-server model you would want. MPD and ncmpcpp function more like a single client with a remote control or like an icecast server with the httpd output in use, whereas Subsonic or CherryMusic have bundled web clients that handle all media playback on their own.

If you wanted to really separate the server and client you could set up the server to only manage the library and expose metadata and media files through the API, then have musikcube rely completely on the API. Then any musikcube instance could connect to an arbitrary core to access the media. All old functionality could be left in by bundling the the ncurses client in with the server so it would look mostly the same, which is what I think Emby does. This really wouldn't be compatible with the icecast model though.

This would also really complicate the plugins, I have absolutely no clue how they are hooked in right now but I would guess the output plugins would be client functionality and the encoding/decoding plugins would make sense in the core. I doubt it would be the best idea to have a plugin model on both the client and the server though. Also, the HTTP server wouldn't technically need to be a plugin in this case since it would be core functionality at that point.

**Comment by clangen** [comment]
> I was looking through the code and if you pulled out all the playback stuff from the core there would really be no logical way to implement a current playback endpoint.

General playback logic, at least related to the hardware the main app is running on, probably _should_ remain in the core. I don't really see a problem with that, as long as APIs exist for external clients to control it. Native plugins can implement an `IPlaybackRemote` interface to manipulate playback, and observe playback-related mutations to the state, including queue-related changes. In fact, the `server` plugin implements the `IPlaybackRemote` interface as a means for remote clients (e.g. `musikdroid`) to control playback.

> I guess it technically depends on how you go about defining the role of the server in this case. Maybe if the server had a separate endpoint for the playback queue of each client. The remote feature would need some work as well to select a specific client for control come to think of it.

I'm not _exactly_ sure what you mean here, but I think it may already exist. Keep in mind, the current server already supports two modes:

1. **Remote Control,** where the client can observe and manipulate the play queue, and issue playback commands (play/pause, prev/next, etc)
2. **Streaming,** where the client can query all metadata in the library, and get HTTP URLs to media resources that can be streamed. Clients can then construct and manage their own play queue however they see fit -- but I think maybe you are suggesting it could also be useful for the server to store client play queues as well?

> I guess the first step would be deciding what kind of client-server model you would want. MPD and ncmpcpp function more like a single client with a remote control or like an icecast server with the httpd output in use, whereas Subsonic or CherryMusic have bundled web clients that handle all media playback on their own.

Right. One of the reasons I prefer the current model is that clients can cache media resources themselves, and make media available to users while the device or server is offline. But again, I agree it'd be nice if audio currently being played on the server hardware could be streamed/multiplexed to multiple clients. 

> This would also really complicate the plugins, I have absolutely no clue how they are hooked in right now but I would guess the output plugins would be client functionality and the encoding/decoding plugins would make sense in the core. I doubt it would be the best idea to have a plugin model on both the client and the server though. Also, the HTTP server wouldn't technically need to be a plugin in this case since it would be core functionality at that point.

Yeah, I really need to document the way plugins work. In general, core deals with everything plugin related -- including interface definition, dynamic loading and selection. In some cases, it exposes these interfaces to native client apps.

**Comment by dkanada** [comment]
I think we have somewhat different ideas for the ncurses app. My personal use case for musikcube will be to install it on a server I don't even have physical access to right now. I will then download the android app and use it entirely in streaming mode because I have absolutely no way to listen to any audio output from the server. Ideally, I would be able to install musikcube on my laptop or desktop and connect to the core on my server where my music is hosted, although currently this isn't possible.

Basically, my thought was that with some changes, the ncurses app could serve the exact same role as musikdroid, or just a frontend to access the music from anywhere. In that situation the current remote control functionality gets super dicey though. Since I can't listen to the audio on my server there would be no point in controlling the playback on that device. How would the remote control feature work on my phone if my laptop and desktop are connected to the server? Also, what happens if I connect my phone to the laptop instead of the server? I wouldn't do that in reality, but how would the software react if the laptop was already connected to the server.

Sorry if I am not explaining myself well enough. The main question is do you want to keep music playback in the core and leave the ncurses app bundled as a frontend interface to the server, or do you want to abstract the core out to only supply data and leave the clients themselves to handle all music playback individually. Regarding the latter, the ncurses app could be ran completely independently of the core similar to musikdroid, but the remote control feature would need to be modified from client->server to client->server->client instead. Also, based on how you are describing the plugin interface it might be infeasible to modify the ncurses app to function as an independent client.

**Comment by clangen** [comment]
> I think we have somewhat different ideas for the ncurses app.

After reading through your most recent post, I actually don't think we're that far off.

> Basically, my thought was that with some changes, the ncurses app could serve the exact same role as musikdroid, or just a frontend to access the music from anywhere.

Yep, with some changes this is totally possible. The required changes would roughly be:

1. Create a C++ WebSocket client that can talk to a `musikcube` server using the existing API.
2. Re-implement all _queries_ using the WebSocket client from (1). In fact, if you look at the existing queries you'll noticed they are already namespaced in a `local` sub-directory because I had eventually wanted to write `remote` versions of them.
    * https://github.com/clangen/musikcube/tree/master/src/core/library/query/local
3. Similar to (2), implement a new `IPlaybackService` that is able to use the HTTP server exposed by the `musikcube` server plugin. In fact, it may not even be necessary to implement a new version of that interface, but instead reuse the existing implementation; if you look closely, the existing code is already capable of streaming audio from a server instance. 
    * https://github.com/clangen/musikcube/blob/master/src/core/sdk/IPlaybackService.h
    * https://github.com/clangen/musikcube/blob/master/src/core/audio/PlaybackService.cpp#L1062
4. Then, of course, write all UI that'd be required to get the user up and running.

> The main question is do you want to keep music playback in the core and leave the ncurses app bundled as a frontend interface to the server, or do you want to abstract the core out to only supply data and leave the clients themselves to handle all music playback individually

Eventually I'd like to support both. The client will be lighter weight and more performant if data doesn't have to flow through through an intermediate server layer, but it would also be great to have that option for the reason you described. It would also allow for users to connect to each others' libraries with relative ease. As a matter of fact, in the **original** implementation of the core library @onnerby added such functionality. Unfortunately, I ripped it out a couple years ago because I just wanted to make a console music app I didn't think anyone would ever use. Oops, huge mistake. 

Also, I see no reason the client and server can't share the same core library and sdk interfaces! Things like encoding/decoding/DSP/etc would be useful for both use cases.

**Comment by clangen** [comment]
You can now stream between clients.
