### ISSUE TITLE
MacOS binaries missing in 0.62.0

### ISSUE THREAD

**Issue by dylanhanning** [clangen/musikcube#237]
Hi, I've downloaded the 0.62.0 MacOS release, and after extracting I only see these files/directories:

- libmusikcore.dylib
- locales/
- plugins/
- themes/

It seems the `musikcube` and `musikcubed` binaries are missing?

**Comment by clangen** [comment]
Yeah, you're right. It looks like `libmicrohttpd` was updated to require `libgnutls` and I was unaware. I happened to not notice on my daily driver because it was already installed; however, it was missing in my build environment and I didn't notice the incomplete build.

This is problematic, though, because static libraries aren't provided for `libgnutls` via homebrew, so I can no longer build stand-alone binaries without changing some stuff around Things will continue to work fine via homebrew, though.

I've gone ahead and removed the bad build binaries from the github release, but need to figure out the best path forward here; it may be just compiling `libmicrohttpd` from source as part of the build process on macOS, and disabling `libgnutls` via configure flag. 

Thanks for the heads up, I'll give this a bit more thought.

For now you can either install via homebrew (recommended) or use the previous version. Sorry for the inconvenience.

**Comment by clangen** [comment]
I just remembered we used to do something very similar for `FreeBSD`. Spent a few minutes dusting off that old code and adding it back for macOS -- we seem to be back up and running. Binaries are here: https://github.com/clangen/musikcube/releases/tag/0.62.2

Thanks again for the heads up!

**Comment by dylanhanning** [comment]
No problem, thanks for looking into it. And thanks for musikcube, it's a great program!
