### ISSUE TITLE
Suggestion: Ignore keyboard layout for hotkeys

### ISSUE THREAD

**Issue by adem4ik** [clangen/musikcube#249]
**Preconditions:**
- Musikcube 0.63.0
- Windows 10 or Manjaro Linux with English and Russian keyboard layouts

1) Start Musikcube
2) Switch keyboard layout to Russian
3) Press "S" to open "Settings"

**Result:** Hotkey doesn't work.
**Expected result:** Hotkey should work as if it was "S" button pressed.

Same thing happens with all hotkeys.

**Comment by clangen** [comment]
Hmm, this is a good suggestion, but I'm not quite sure how to make it work without introducing some sort of mapping. I'll do a bit of research and see what I can find.

However, I did notice on Windows if I change my keyboard type to ru_RU, search doesn't seem to work properly, that is, the cyrillic characters don't show up at all. I think I figured out a way to hack around this, but I'm just curious: have you had the same problem?

**Comment by clangen** [comment]
I could introduce a section of the locale file where we map the standard/default hotkeys to locale-specific hotkeys. Do you see any issues with that?

**Comment by adem4ik** [comment]
> search doesn't seem to work properly, that is, the cyrillic characters don't show up at all.

Yes, I have the same problem. Also if I try to change "key bind" to cyrillic one it shows up as "Unknown key".

> I could introduce a section of the locale file where we map the standard/default hotkeys to locale-specific hotkeys.

I think that may work. But will it work if user change the default hotkey to some other? I guess the mapping section should have all possible keys, not only standard ones.

**Comment by clangen** [comment]
> Yes, I have the same problem. Also if I try to change "key bind" to cyrillic one it shows up as "Unknown key".

Yikes, this is really bad. I'll get this fixed for the upcoming release (probably today or tomorrow). 

> I think that may work. But will it work if user change the default hotkey to some other? I guess the mapping section should have all possible keys, not only standard ones.

I'll need to think this over a bit more, but I was originally thinking that the locale file could just have a mapping for default hotkeys only... but I actually think this is a bad idea -- just because you have a particular language selected, doesn't mean you have the keyboard for that language enabled. It may be better to separate default keyboard shortcuts from language files. So we'd have some file like `default_hotkeys_RU.json`, that would look like the `hotkeys.json` described here: https://github.com/clangen/musikcube/wiki/vi-style-navigation-keys, but would have the equivalent bindings for a Russian keyboard layout.

**Comment by clangen** [comment]
FYI, I released 0.64.0, which should fix input for non-Latin characters in Windows.

**Comment by adem4ik** [comment]
> FYI, I released 0.64.0, which should fix input for non-Latin characters in Windows.

I confirm that, now it is possible to bind cyrillic character as a hotkey, searching works now too. Thanks!
