### ISSUE TITLE
[request] XM audio support

### ISSUE THREAD

**Issue by azev** [clangen/musikcube#281]
Equalizer, essential in any player.

Module format support: https://en.wikipedia.org/wiki/XM_(file_format)

**Comment by clangen** [comment]
An equalizer is already included -- just press `CTRL+e` in the library or player views.

**Comment by azev** [comment]
https://en.wikipedia.org/wiki/XM_(file_format)

**Comment by clangen** [comment]
Something like this may be useful: https://lib.openmpt.org/

**Comment by ogrim** [comment]
I am interested in having support for module formats as well, as it will be far superior to use musikcube than any other weird player. I'm currently using XMPlay for modules - but that is just kind of Windows 95 in the bad way.

Would it be possible to add playback formats to musikcube using input plugins?

**Comment by clangen** [comment]
This is something I've wanted to do for a while, and finally got around to it today -- it seems to be working. Needs some cleanup and additional testing, but there's a branch here: 

https://github.com/clangen/musikcube/pull/354

It'll be part of the next release.

**Comment by ogrim** [comment]
Sweet! 🙌 Looking forward to trying it out :)

**Comment by clangen** [comment]
So it seems very common for mod / xm / tracker files to not contain artist or album metadata -- curious how you folks that are interested in the feature would think about grouping / sorting these entries? I guess we can have default `[unknown xm artist]` and `[unknown xm album]` values, then allow the user to configure them in settings. Is there any better solution? 🤔

**Comment by ogrim** [comment]
Most mod collections are grouped in folders - so I will be using the directory listing for this (as I do for all other music anyways).

Here I have searched for folders in the Modland collection by the artist Maktone. I found multiple, but opened only two of them.

Here it is ordered into module formats before the artist folder. Here Protracker and SNDH and then Maktone:

![image](https://user-images.githubusercontent.com/296455/84706937-1f970900-af5e-11ea-906d-44e181d4adcf.png)

To find all the other Maktone folders, I would like to be able to search on folder names only.

On another note, artist usually will write stuff in the sample listings - but since this is just freetext I don't see myself sorting on it or searching for it. But I think it is very important to see this listing when playing the tunes!

![sohx1pNmmi](https://user-images.githubusercontent.com/296455/84707038-49503000-af5e-11ea-9742-4e15e8b6627d.png)
