### ISSUE TITLE
Transcoding into Opus

### ISSUE THREAD

**Issue by alfureu** [clangen/musikcube#290]
Any chance to transcode files into opus, providing an option to select instead of mp3? Mostly for mobile data use for Android devices: http://opus-codec.org/comparison/

**Comment by clangen** [comment]
I want to see if I can find a time writing an `IEncoder` plugin that uses `ffmpeg`. If I can do that, we should be able to transcode to pretty much any format imaginable (and as a bonus, can probably ditch our `libvorbis`, `libogg` and `libmp3lame` dependencies)

**Comment by clangen** [comment]
Been playing with this the past few days -- I managed to get it working fine on macOS and Linux, but am having problems on Windows. That may be a deal-breaker. I'm going to continue playing with it, but I'm currently going in circles, perhaps due to my lack of knowledge of the inner workings of libav. 

Progress can be tracked in this PR: https://github.com/clangen/musikcube/pull/297

**Comment by clangen** [comment]
Got it working on Windows -- I think this is a good candidate for next release. I need to do some memory leak testing first, though.

**Comment by clangen** [comment]
This has been merged back for the next version.
