### ISSUE TITLE
ALAC/m4a files with disc numbers are not sorted correctly in Browse view

### ISSUE THREAD

**Issue by infinitejones** [clangen/musikcube#293]
Running musikcube on MacOS 10.15.2

When viewing m4a files with tags updated by MacOS iTunes, files in the same album with differing disc numbers are not sorted correctly.

They appear as 1,1,2,2,3,3,4,4 etc instead of 1,2,3,4,1,2,3,4

Files in the same album in MP3 format, with tags also updated by MacOS iTunes, do display correctly based on their disc number (ie 1,2,3,4)

In the attached screenshot, discs 1+2 of a 4-album set are ALAC and discs 3+4 of the set are MP3. 

Discs 1 and 2 are sorting 1,1,2,2,3,3,4,4 etc and 3+4 are sorting 1,2,3,4,1,2,3,4
![Greenshot 2019-12-13 12 11 52](https://user-images.githubusercontent.com/5801868/70761628-ef4d9280-1da1-11ea-944e-5aa43e122515.png)

**Comment by clangen** [comment]
Thanks for filing this issue, it will be fixed in the next release!

Note: annoyingly, you'll need to rebuild your library to see it take effect, which can take a few minutes. In musikcube press `CTRL+r` in library view, and select `rebuild library` after upgrading when the new version is released.

https://github.com/clangen/musikcube/pull/295/commits/a6df6c9c21b4e24e956c2d4e97bdab72f27a40ce

**Comment by ghost** [comment]
Greetings, Im still having this issue in version 0.97.0 (Tags were correctly modified by me using Kid3 and all my files are in AAC/M4A CBR 256kbps).
![2022-04-12-224608_1366x747_scrot](https://user-images.githubusercontent.com/95720679/163089928-2aba57d4-b6b6-4768-a824-c4db688fc829.png)

**Comment by spinicist** [comment]
I'm still seeing this issue as well:

![image](https://user-images.githubusercontent.com/11050744/210778181-be15b7f2-dbf0-406d-993e-0fb2f9a6a058.png)
