### ISSUE TITLE
Black border is shown when window is maximized

### ISSUE THREAD

**Issue by adem4ik** [clangen/musikcube#305]
**Preconditions:** musikcube 0.80, Windows 10 x64, 1600x900 screen resolution

1) Start musikcube
2) Maximize its window

**Expected result:** no border is shown
**Result:** black border is shown at the bottom part and the right part of the screen
![image](https://user-images.githubusercontent.com/4707112/72198569-ae03dd80-3448-11ea-8ea2-8bca73491989.png)

**Additional info:**
Issue is presented in any version of Musikcube. I haven't used Musikcube on Windows for like 2-3 months, but I don't remember that Musikcube had such issue in the past. So I guess it is not Musikcube issue, it could appear somehow recently after some Windows updates or after my changes of settings in my system. It would be nice if someone could try to reproduce that issue on his PC.

**Comment by adem4ik** [comment]
Issue is reproduceable in Musikcube 0.70 on Linux Manjaro, so my previous assumption is wrong:
![image](https://user-images.githubusercontent.com/4707112/72198869-469c5c80-344d-11ea-908f-90391b9f5c09.png)

**Comment by clangen** [comment]
Unfortunately I don't think there's much we can do about this bug. Because console apps are monospaced, each character takes up a pre-defined a mount of space. If the window is resized such that the remainder is less than a full character width, the terminal's default background color will be drawn in that space (in most cases, this is black or white, depending on the theme).

If it's annoying, you can try to enable the `enable transparency support` setting, which should set the global background color to transparent, which will mask the issue.

**Comment by adem4ik** [comment]
@clangen Thanks for explanation, that got me an idea to mask it in another way - by changing font and its size from the Musikcube menu.

For example on Windows - Consolas 11:
![image](https://user-images.githubusercontent.com/4707112/74601316-3152c780-50b6-11ea-8a58-681654f6c336.png)
