### ISSUE TITLE
Opening in Conemu

### ISSUE THREAD

**Issue by dinesh0430** [clangen/musikcube#313]
Is there a way to open musikcube in conemu and not seperate window?

**Comment by clangen** [comment]
It's not currently possible, but should be achievable. Right now we link against a specific version of the curses library on Windows that uses a "native" window and emulates console behavior -- that's because it has higher fidelity font rendering, or at least did on older versions of Windows. There's another variant of curses that runs as a true console app that we should be able to link against instead, and generate a separate `exe` that runs within cmd.exe or conemu.

Let me give this a little bit of thought to see if I can figure out a low-cost way to generate the other variant.

**Comment by clangen** [comment]
Here's a proof of concept -- it seems to work well:

![image](https://user-images.githubusercontent.com/2031666/74097094-e4229480-4abc-11ea-8290-eafc60a3fe97.png)

I still haven't figured out how to automate building it, though.

**Comment by dinesh0430** [comment]
Thanks for responding, I will waiting for this feature!

**Comment by dinesh0430** [comment]
If you somehow manage to get this right and working, please mention it in the changelog of the upcoming version of musikcube. 
Enjoy your weekend!

**Comment by clangen** [comment]
Alright, I think I worked out all the logistics. This will be part of the next release.
