### ISSUE TITLE
MusikDroid on Google Play Store

### ISSUE THREAD

**Issue by simolev** [clangen/musikcube#363]
Why isn't MusikDroid published on the Google Play Store?
If it were, the app would be able to auto-update, thus saving the small hassle of doing it manually (reading the popup that announces a new version, dismissing it, then manually downloading and installing the apk).

On one hand, it is really a small inconvenience not having the app on the Play Store.
On the other hand, it being there could have the nice side effect of boosting this project's popularity.

I see the author already published two apps ([Plasma Live Wallpaper](https://play.google.com/store/apps/details?id=org.clangen.gfx.plasma) and [PopSquares Live Wallpaper](https://play.google.com/store/apps/details?id=org.clangen.gfx.popsquares)), so there has to be a catch I'm unaware of. What's the explanation? Can the issues be somehow overcome?

**Comment by clangen** [comment]
I've gone back and forth on this many times over the years. The primary reason `musikdroid` isn't on the Google Play Store is that I have concerns that, because it requires a `musikcube` server to function, many novice users will download the app, not understand how to use it, then leave negative feedback and tank the rating. Such feedback can be worse than no feedback at all, and scare potential users away from the project.

I've also toyed with the idea of releasing it on [F-Droid](https://f-droid.org/), which is not nearly as common, but likely has many more advanced users.

**Comment by simolev** [comment]
Thanks for the explanation: I now understand your dilemma.
If it were me, I would go forward with it: just add the github link and a warning "Only download if you have a working MusikCube server", such as I have seen on several specialized apps that require their respective backend.

Let me reiterate that the hassle is really small; moreover, it gives the pulse of how active development is, and it's good to see that updates are relatively frequent.

Success in terms of rating is not guaranteed, so if that's your concern I'll just close the issue for now.
Please reopen in the future if you start considering this again and want to discuss it further.
