### ISSUE TITLE
Generate DLL headers?

### ISSUE THREAD

**Issue by hacker1024** [clangen/musikcube#369]
Hi, I'm trying to build a Musikcore DLL on windows. The build runs successfully, and lib and exp files are generated - but no headers.
Is there a way to generate the headers? Are they supposed to be copied straight out of `src/`?

This isn't covered in the wiki or README.

**Comment by hacker1024** [comment]
Never mind, I see in the cmake script that they're at `src/core/sdk/*.h`.

**Comment by clangen** [comment]
Also, there is a very thin wrapper on top of the SDK API for C (instead of C++) that may be easier to use, especially when inter-operating with other languages. The DLL (or shared library on *nix) should already export all the required symbols. 

While it's largely undocumented, it should map very closely to the C++ API.

Here's the header: https://github.com/clangen/musikcube/blob/master/src/core/musikcore_c.h

And a small demo app in C: https://github.com/clangen/musikcube/blob/master/src/core_c_demo/main.c

**Comment by hacker1024** [comment]
Yup, I realised just after closing. Thanks for mentioning it.
