### ISSUE TITLE
Quick jump to items starting with a letter in long artist/album lists in the library view

### ISSUE THREAD

**Issue by dbogdanov** [clangen/musikcube#376]
When browsing by artist/album/album artist/genre/playlist one can have too many items to scroll down when searching. It will be useful to have a hotkey to jump to an artist/album/etc. starting with a particular letter. 

For example, press `j` then `l` to jump to the artists starting with letter `L` in the artist list.

**Comment by clangen** [comment]
Yeah, this has been requested a few times and also something I want. I've been dragging my feet because I can't figure out a good UI for it. We can't just process regular keystrokes because many of them are used for other bits of functionality, like controlling playback and switching views.

It will probably need to be something like a short sequence: `Ctrl+J` to enter "jump to" mode, followed by a letter like `L` or something.

**Comment by clangen** [comment]
After a bunch of back and forth, eventually we just added an inline filter to the browse window, which can be activated by `^F`
