### ISSUE TITLE
Sort shortcut is already a shell function

### ISSUE THREAD

**Issue by itsdeadguy** [clangen/musikcube#419]
Hi, the shortcut `^S` which the program uses for sorting tracks is defined by `stty` as "stop output", which means using it freezes the terminal.
Output can be resumed with `^Q` but maybe you should consider changing the default? it's easy enough to rebind to something else, fortunately.

Loving the software, thank you for creating it.

**Comment by clangen** [comment]
Sorry for the delay, real life has been busy for a while. :)

Thanks for the report! I just changed the default to `M-s` instead of `^S`. Existing users will have to rebind the value themselves, or delete `~/.config/musikcube/hotkeys.json`, but it should not be a problem for new users moving forward.

Commit for reference: https://github.com/clangen/musikcube/commit/a28d14717d48928ccad947d3cc02ecce547494e7
