### ISSUE TITLE
Musikdroid Android 4.2.2

### ISSUE THREAD

**Issue by pualt164i** [clangen/musikcube#422]
There's any version of musikdroid that runs in Android 4.2.2, with all its functions?

**Comment by clangen** [comment]
Sorry, it's not officially supported. You can try to change the `minSdkVersion` to `17` in the `build.gradle` file here: https://github.com/clangen/musikcube/blob/master/src/musikdroid/app/build.gradle#L19, and it'll probably build with minimal fuss, but I know there used to be some minor UI glitches that were difficult to work around. Because Android 4.x isn't widely used anymore, and I don't have tons of spare time to work on the project, I discontinued support for it a while back.
