### ISSUE TITLE
Build Instructions not up-to-date

### ISSUE THREAD

**Issue by BlueberryDoesLinux** [clangen/musikcube#434]
Title says it all. I'm on Ubuntu 20.10 and none of the Ubuntu deps work. Would be nice if this could be updated

**Comment by assarbad** [comment]
On `focal` (20.04) I got away with the following:

```
sudo apt-get install cmake libogg-dev libvorbis-dev libavutil-dev libavformat-dev libswresample-dev libncursesw5-dev libasound2-dev libpulse-dev pulseaudio libmicrohttpd-dev libmp3lame-dev libcurl4-openssl-dev libev-dev libssl-dev libtag1-dev libopenmpt-dev
```

... apparently the boost libraries were already included with something else (on my system they were marked `auto`). However, if that's not the case for you, perhaps try the package names without explicit version number. That worked for me. So in this case:

```
sudo apt-get install cmake libogg-dev libvorbis-dev libavutil-dev libavformat-dev libswresample-dev libncursesw5-dev libasound2-dev libpulse-dev pulseaudio libmicrohttpd-dev libmp3lame-dev libcurl4-openssl-dev libev-dev libssl-dev libtag1-dev libopenmpt-dev libboost-thread-dev libboost-system-dev libboost-filesystem-dev libboost-date-time-dev libboost-atomic-dev libboost-chrono-dev
```

What I found curious during the build, however, was that while CMake appeared to honor my override of `CXX` and `CC`, later stages of the build reverted to `gcc` and `g++`. So I'll rerun it with overriding the variables also in my `make` invocation.

**Comment by gschauer** [comment]
I guess the `CMakeLists.txt` wasn't updated back then. That's unpleasant but only a minor issue.
Simply updated the file with the versions from `script/install-deps.sh` or whatever versions are available in your distro.
Once you've done that, you could build it yourself and don't need to wait for another release.

Meanwhile, Ubuntu 20.10 reached the end of support, but there's a the same issue with Ubuntu 21.10.
The dependencies in CMakeLists.txt haven't been updated in commit fe2e474.
So I did that in https://github.com/gschauer/musikcube/commit/566f248aee465d718f738d9071b99d3f6c6d91d4.
Moreover, I took the liberty and added Debian Bullseye to the CircleCI build, because it was partially added in the afore-said commit.

Please consider PR #475.


PS: For everyone, who needs to build musikcube from source but doesn't want to install dozens of libraries:
If you've Docker installed, you could do something like:

```bash
cmd="apt update &&
  apt-get install -y --no-install-recommends ca-certificates git &&
  git clone https://github.com/clangen/musikcube.git --recursive &&
  cd musikcube &&
  grep -F ubuntu:impish -A 9 .circleci/config.yml | grep -E "install|make" | cut -d : -f 2- | xargs -I {} bash -c {} &&
  cp musikcube*.deb /root/debs"

docker run -it -v /tmp/musikcube:/root/debs ubuntu:21.10 /bin/bash -c "${cmd}"
```

Needless to say, adjust `<USERNAME>` and the distro accordingly, if you want to build your fork for a certain distro.

**Comment by clangen** [comment]
The change mentioned above was merged, and a new build has been released! Resolving this for now, please re-open if there are still issues.
