### ISSUE TITLE
Unable to use release macos binary

### ISSUE THREAD

**Issue by vkuznet** [clangen/musikcube#468]
```
# untar
tar xvfj ~/Downloads/musikcube_macos_0.96.5.tar.bz2
cd musikcube_macos_0.96.5/
# change attributes to allow run the executable
xattr -d com.apple.quarantine musikcube

# run the executable
./musikcube
dyld: Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib
  Referenced from: /Users/vk/tmp/musikcube_macos_0.96.5/./musikcube
  Reason: image not found
```

Can you provide a way to use different libssl (from different location)?

Or, can you provide build to macports?

**Comment by clangen** [comment]
Moving forward we will not be supplying macOS binaries, at least for a while; My Intel Mac recently died, and I have no way to build standard x64 mac binaries.

I'll try to look into adding a macport, but it may be difficult for me because I use homebrew, and I'm not sure how peacefully the two will co-exist on the same computer.

**Comment by davidebeatrici** [comment]
@clangen MacStadium offers an hosted Mac for open-source projects: https://www.macstadium.com/opensource-application

We currently rely on them to build Mumble binaries.

**Comment by clangen** [comment]
I have managed to get my old Intel macbook working again, so pre-compiled binaries for Intel mac are back again, better than ever as they do not require additional dependencies via homebrew: https://github.com/clangen/musikcube/releases/
