### ISSUE TITLE
Why do not you want?

### ISSUE THREAD

**Issue by 237dmitry** [clangen/musikcube#487]
1. Get rid of the musikcube-cmd stump in favor of a full-fledged musikcube.exe which will run as a full-fledged console application?
2. Compile statically and release as an archive for Linux?

НNY!

**Comment by clangen** [comment]
Good questions!

1. `musikcube-cmd.exe` is definitely not a stump, or wrapper, or special launcher anything like that. It _is_ a fully fledged console application on Windows. It's compiled separately from `musikcube.exe` and does not depend on it in any way. Unfortunately, the Windows console is limited to 8 (or 16?) colors that the application cannot configure, so themes won't work -- that's why `musikcube.exe` is distributed with it; it allows users (like me) who want a better user experience to have that option.

2. I'd absolutely **love** to statically link against all dependencies on Linux, but I have not had success linking boost statically on Debian based distros (Debian, Ubuntu, Mint, etc). I receive error messages along the lines of `relocation R_X86_64_PC32 against symbol '...' can not be used when making a shared object; recompile with -fPIC`. From what I can tell, this is caused by the way boost is compiled (see: https://stackoverflow.com/a/34419321). Unfortunately, short of re-compiling boost on every version of every Debian-based distro we support, I'm not sure what else can be done.

**Comment by 237dmitry** [comment]
> the Windows console is limited to 8 (or 16?) colors that the application cannot configure, so themes won't work 

But it's not like that. The console in Windows supports rgb and almost all esc sequences.

![ss-20220101195632](https://user-images.githubusercontent.com/78153320/147855767-f21da8d4-1067-4e9d-a8a4-73ee074d30ca.png)

Please, add themes support to musikcube-cmd.exe. 

I would use musikcube.exe, but it runs in its own window and it cannot be run in a tab or split pane of Windows Terminal.

**Comment by clangen** [comment]
Oh, cool! Thanks for making me aware of true color support in Command Host / Windows Terminal. I pushed a patch that will enable it in subsequent builds: https://github.com/clangen/musikcube/commit/d77bf3c8332f04ffe8fbd14c1662e96727430ae3

**Comment by 237dmitry** [comment]
Thank you for `musikcube-cmd.exe` theming and for linux "standalone" builds.

**Comment by clangen** [comment]
@237dmitry if you see this, did the "standalone" Linux build work for you without issue? Just curious. :)

**Comment by 237dmitry** [comment]
Musikcube for linux works without any problems. In any case, I didn't see any. ArcoLinux. Unpacked to /opt, symlinked to $PATH and launched.
