### ISSUE TITLE
artist features are combined into new artists

### ISSUE THREAD

**Issue by strelizia1312** [clangen/musikcube#524]
hey :)
when my songs are tagged with more than one artist, musikcube will take those two artists and turn them into a new one in the artists library bar, but I don't want to have 14 different menus of the same artist and instead have one song that is tagged with "artist1, artist2" shown under both artist1 and artist2 instead of a new artist called "artist1 artist2"

I'll attach an example
![issue](https://user-images.githubusercontent.com/97415893/169649512-37956b96-459d-45f7-8dbb-1b264b1523c6.png)

**Comment by ghost** [comment]
This issue is maybe related to my request. Please use the album artist as a way to sort by artists, that way when I e.g. have a genre CD called Classics V2, I can but that name as an album artist. That way not all titels of this genre CD get listed as a separate artist in the list that @alinawallpainter showed.

**Comment by clangen** [comment]
Yep, in this case you can just change the view from "artist" to "album artist" and it should fix your issue.

**Comment by NicTanghe** [comment]
where does one change the vieuw from artist to album artist ?
