### ISSUE TITLE
Crash on scanning music directory

### ISSUE THREAD

**Issue by adem4ik** [clangen/musikcube#542]
**OS:** Manjaro KDE
**Version:** 0.98 (from [AUR](https://aur.archlinux.org/packages/musikcube))
**Sound system:** Pipewire 0.3.56 (Pulseaudio isn't installed)

1. /home/user/.config/musikcube/ is cleaned
2. Start Musikcube
3. Add a music directory to `music paths`
4. Wait for syncing

**Result:** Musikcube crashes with the following console output:
![2022-08-22_01-31](https://user-images.githubusercontent.com/4707112/185811981-ab0ffa21-6d03-468d-9f77-00bbed749de0.png)

**Log:** [log.txt](https://github.com/clangen/musikcube/files/9389982/log.txt)
**Stderr:** [stderr.txt](https://github.com/clangen/musikcube/files/9389983/stderr.txt)

```
~ >>> inxi -A                                                                 
Audio:
  Device-1: Intel 6 Series/C200 Series Family High Definition Audio
    driver: snd_hda_intel
  Device-2: NVIDIA GP106 High Definition Audio driver: snd_hda_intel
  Sound Server-1: ALSA v: k5.15.60-1-MANJARO running: yes
  Sound Server-2: PipeWire v: 0.3.56 running: yes
```

**Comment by clangen** [comment]
These types of crashes can be super annoying to root-cause. In most cases they are due to corrupt metadata -- if that's the case, and I can get my hands on the problematic file, I can probably fix the issue. 

Try the following: 
1. If possible, restore musikcube to its default state by removing the `~/.config/musikcube` directory
2. Open `musikcube`, go to `settings` > `advanced settings`
    - `IndexerLogEnabled`: `true`
    - `IndexerThreadCount`: `1`
3. Add your directory and wait for the indexer to scan the metadata. It'll be much slower than usual because it's only going to use one processor core to scan files one at a time, adding them to a log file as it goes.
4. When the app crashes, take a look at `~/.config/musikcube/indexer_log.txt` -- at the very end it should show the filename of the last file that it processed; the crash will either have occurred with that file, or the next file which should be easy to figure out by listing files in the directory.

If you're able to find the problematic file I'd love to get a copy of it to see if I can fix the issue.

**Comment by adem4ik** [comment]
Thanks for explanation. I've found 3 tracks with such issue:
[tracks part1.zip](https://github.com/clangen/musikcube/files/9390153/tracks1.zip)
[tracks part2.zip](https://github.com/clangen/musikcube/files/9390154/tracks2.zip)

**Comment by clangen** [comment]
Got it, the crash was caused by a bug in a string whitespace trim method in the metadata scanning plugin. This commit should fix it: https://github.com/clangen/musikcube/commit/52fe847bfade6534c3c17fdb34a6e7f85245d9a6

**Comment by adem4ik** [comment]
Checked on manually build git-version - it is fixed now, thank you!

**Comment by clangen** [comment]
https://github.com/clangen/musikcube/releases/0.99.0
