### ISSUE TITLE
Musikdroid doesn't recognize output device of musikcubed 

### ISSUE THREAD

**Issue by jondoe1337** [clangen/musikcube#557]
When running musikcubed as a remote streaming instance and connecting to that instance with musikdroid, playing audio with it (in remote mode) doesn't work. 

Opening "remote management" shows only "default" for the "output device". 

However it works if I start musikcube in foreground (and then connect to it). 

Any ideas how to track this down? Is it maybe a config problem?

**Comment by clangen** [comment]
That's really strange -- I just tried on both my Linux and Mac installations and it seems to work fine. What platform/OS are you using, and which versions of musikcube and musikdroid? :)

**Comment by jondoe1337** [comment]
Musikcubed runs on a raspberry PI using raspbian 10 (buster) at `0.98.0_armhf`. 

Musikdroid runs on Anroid 12 running `0.98.1`.

If I run musikcubed in foreground I see the audio devices (other than default) in musikdroid btw.

The musikcubed is started using the systemd script:

```
[Service]
Type=forking
User=pi
ExecStart=/usr/bin/musikcubed --start
ExecStop=/usr/bin/musikcubed --stop
```

**Comment by clangen** [comment]
Hmm... is the `pi` user a member of the `audio` group?

**Comment by jondoe1337** [comment]
Yes he is. When running it in foreground I'm using the same user btw.

**Comment by jondoe1337** [comment]
This is a `ps aux` output for the service running:
```
pi       26544  8.1  2.8 769956 27292 ?        Ssl  22:05   0:17 ./musikcubed --start`
```

and this as the forground process:
```
pi       26707 18.5  3.1 199816 30048 pts/1    Sl+  22:10   0:02 ./musikcube
```

What is also interesting is that I see ALSA output devices when running in background (but no Pulse), however it doesn't work either. Running in foreground it works for both output drivers.

**Comment by clangen** [comment]
Sorry, I've been busy with hardware failures for some of my other projects that have been consuming a lot of my time.

You're right, I can repro the problem, but only when starting the service with systemd. I'm not quite sure what's wrong, though. I'll keep poking around to see if I can figure out what's going on.

**Comment by clangen** [comment]
OK, so let me be the first to admit that while I know my way around a UNIX system, it's definitely not my area of expertise; that said, I was able to make a bit of progress with this issue.

From what I can tell when using `systemd` the `pulseaudio` daemon runs as a "user" service, that is, it does not run as a system-level daemon, and different instances spawn for different users on the operating system on demand. 

The configuration file you've specified runs `musikcubed` as a "system" (i.e. non-"user") service as a different user. 

I stumbled upon this question/answer on StackOverflow: https://stackoverflow.com/a/27091782

So it would seem that the `musikcubed` service, as configured, will not have access to all of the environment variables required to establish a connection to the `pulseaudio` daemon. That seems strange to me, but it does indeed seem to be the case. If we create a new "user"-service as follows:

Filename: `/etc/systemd/user/musikcubed.service`

Contents:
```
[Unit]
Description=musikcube daemon

[Install]
WantedBy=default.target

[Service]
Type=forking
ExecStart=/usr/bin/musikcubed --start
ExecStop=/usr/bin/musikcubed --stop
```
We can start it like this: 
  * `systemd --user enable musikcubed.service`
  * `systemd --user start musikcubed.service`

Then the service will will be able to query `pulseaudio` for devices successfully. Unfortunately, because it's a "user" service, it won't be started until the user logs in. 

So, if you want to manage `musikcubed` using `systemd` I believe there are two options:
  1. Figure out how to run `pulseaudio` as system-level service. I worry there are security implications doing this, as now all users would potentially have access to the running service.
  2. Figure out how to make the `musikcubed` system service start without the user logging in. I did some searching and I'm not sure how to do this, or if it's even possible. 

I'll keep fiddling around with this for a bit, but hoping someone with more experience using `systemd` will be able to help us find a clean solution.

**Comment by clangen** [comment]
Also, for what it's worth, this is how I started `musikcubed` on boot on my rpi:

1. Open `/etc/rc.local`
2. Add the line `su - pi -c musikcubed`
3. reboot

This seems to work fine. I experimented with using this as the start command in my `musikcubed.service` file, but it doesn't seem to work properly, but I'm unsure why.

**Comment by jondoe1337** [comment]
Apologises for my late reply, x-mas was on 🎄 happy new year btw - and thanks for checking in. To be honest I'm also not that deep into systemd, but of course you're right. To fix the issue with a user service that is started at login just do `loginctl enable-linger pi`, which is persistent. After that a shadow process is started at boot for that user so that user services can be forked. Last step to fix it was to remove the `User` setting from the `[Service]` description. 

Now everything works 🎉 

Edit: also had to change the `WantedBy` target to `default.target`
