### ISSUE TITLE
0.99.5 Milkdrop plugin not loading (x64)

### ISSUE THREAD

**Issue by 237dmitry** [clangen/musikcube#575]
In 0.99.5 release notes:

```
fixed milkdrop2 plugin to work on 64-bit machines, and include it by default for both win32 and win64 releases.
```
But this plugin is not loaded in either musikcube.exe or musikcube-cmd.exe.
There is milkdrop2.dll in plugins.json, but it is not in the `configure plugins` section.

**Comment by clangen** [comment]
Do you have the DirectX 9 runtime installed? You can get it from here: https://www.microsoft.com/en-us/download/details.aspx?id=8109.

**Comment by 237dmitry** [comment]
> Do you have the DirectX 9 runtime installed?

`dxdiag` shows DirectX 12. Must be 9?

**Comment by clangen** [comment]
I have to admit I know _very_ little about graphics programming -- I just ported the existing code over to a musikcube plugin. But I'm pretty certain you have to install the DirectX 9 version specifically, as it's not included as part of DirectX 12.

**Comment by 237dmitry** [comment]
I understand. May I ask, instead of creating a new issue, can you add visualization [projectM](https://github.com/projectM-visualizer/projectm?ysclid=ldtwnptunt425618407) as a plugin to your wonderful player? On the Linux platform.

**Comment by clangen** [comment]
Great call-out! I've been working on porting the upcoming projectM "v4" release for the past week or so... it's running on Windows and Linux, but unfortunately I'm having issues on macOS (on my M1) that I'm struggling to debug because I know nearly nothing about graphics programming.

Here's the branch/PR: https://github.com/clangen/projectM-musikcube/pull/1

I'll keep messing around with it, but can't make any promises. :)

**Comment by clangen** [comment]
Closing this issue -- I'm still considering a `projectM` port, but I just haven't had time to do it yet.
