### ISSUE TITLE
Can't play any music

### ISSUE THREAD

**Issue by Iseja** [clangen/musikcube#590]
Running endeavour OS, everything is up to date installed through the AUR.
Could play music a couple of days ago but not today. When I tried the logs only say:
[streams] nothing could open 

Have tried to reinstall without success

**Comment by rodrigomessias** [comment]
This happened to me on Manjaro, managed to get it playing again by switching from 'musikcube' to 'musikcube-bin' package from the AUR

**Comment by 237dmitry** [comment]
This has never happened because I use the static build from the releases page.

**Comment by clangen** [comment]
A new major version of ffmpeg was recently released, and it sounds like the library names changed, which caused the decoder plugin to stop loading.

If you compiled `musikcube` from source (which happens when you install the `musikcube` package from AUR), you'll simply need to reinstall it. It'll detect the updated library names and link against those.

Alternatively, you can install the `musikcube-bin` package from AUR, which will not have this issue because it includes all of the required dependencies.

Like @237dmitry mentioned, you can also install the static builds from the releases page on github; (note that the `musikcube-bin` AUR package is created from these, or at least used to be).
