### ISSUE TITLE
0.99.8: Build fails with fatal error: 'taglib/tlist.h' file not found

### ISSUE THREAD

**Issue by yurivict** [clangen/musikcube#600]
```
In file included from /usr/ports/multimedia/musikcube/work/musikcube-0.99.8/src/plugins/taglib_plugin/taglib_plugin.cpp:36:
/usr/ports/multimedia/musikcube/work/musikcube-0.99.8/src/plugins/taglib_plugin/TaglibMetadataReader.h:40:10: fatal error: 'taglib/tlist.h' file not found
#include <taglib/tlist.h>
         ^~~~~~~~~~~~~~~~
```

Build fails after configure succeeds. taglib-1.13 is installed.

It looks like the output of this command was lost in configure:
```
$ pkg-config --cflags taglib
-I/usr/local/include -I/usr/local/include/taglib 
```

**Comment by clangen** [comment]
Weird. There have been some refactors to our `cmake` scripts to support some new targets, but nothing related to `taglib` since December 21st, 2022 (version 0.99.1).

I don't currently have a working `FreeBSD` installation -- will try to get that sorted soon, but I'm curious if that header file (`<taglib/tlist.h>`) exists on the system that's doing the build? 

> It looks like the output of this command was lost in configure:

Can you explain a bit about what you mean by that? What does "lost" mean in this context? :)

**Comment by yurivict** [comment]
Adding -I/usr/local/include to CXXFLAGS allows it to build successfully. This header exists: /usr/local/include/taglib/tlist.h

This leads me to believe that pkg-config's output is ignored.

**Comment by clangen** [comment]
@yurivict got it, thank you for the report. Got a new FreeBSD VM up and running and believe I fixed the issue. Changes have been pushed to master, and will be released within the next couple days.

**Comment by clangen** [comment]
This has been fixed and released.
